name: Release HA Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
  
      - name: Fetch docs from other repos
        run: |
          mkdir -p ./docs/fuel_prices_sweden
          wget -N https://raw.githubusercontent.com/deler-aziz/fuel_prices_sweden/main/README.md -P ./docs/fuel_prices_sweden
         

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto update documentation
          branch: update-docs
          delete-branch: true
          title: 'Auto update documentation'
          body: |
            Auto created PR to merge READMEs into main branch
          labels: |
            automated pr
        